.gitignore
Gemfile.lock

first commit

---

app/models/vehicle.rb

Created all validations for Vehicle

Validate vehicle

---

Gemfile.lock
db/migrate/20220303145547_change_price_on_vehicles.rb
db/schema.rb

Manu,
preço do model atualizado de float para decimal

Update price vehicle model

---

app/controllers/vehicles_controller.rb
config/routes.rb

added destroy route and method

add detroy

---

config/routes.rb

fixed singular vehicle to vehicles

vehicle to vehicles in routes

---

app/controllers/vehicles_controller.rb

fix index route

---

app/controllers/application_controller.rb
app/controllers/vehicles_controller.rb
app/models/user.rb

Manu,
parte do Devise action para mostrar certas páginas apenas se estiver logado foi implementada.

before action and skip before action implementation

---

app/controllers/vehicles_controller.rb

add destroy to before_action set_vehicle

set vehicle before destroy

---

app/models/order.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
db/migrate/20220303205716_create_orders.rb
test/models/order_test.rb

Agora sim o código do model no lugar certo.

Add Order model

---

app/controllers/vehicles_controller.rb
app/views/vehicles/show.html.erb

Still needs some fine tuning but looks better

Better vehicle show view

---

app/views/devise/registrations/edit.html.erb

Add edit photo on profile

---

app/controllers/orders_controller.rb
app/controllers/vehicles_controller.rb
app/views/vehicles/index.html.erb
db/schema.rb

Views orders2

---

.gitignore
app/views/shared/_navbar.html.erb

fixed avatar and some links, still need to add logout

fix avatar and links

---

app/views/shared/_navbar.html.erb

Add logout navbar

---

app/views/vehicles/show.html.erb

added edit link to vehicle show

add edit to vehicle show

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/views/vehicles/index.html.erb

has some conflicts, will try to fix it here

fix index view a bit

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb
app/views/vehicles/index.html.erb

Added hero to home and aligned the Title from the navbar to the left (the centered alignment clashed with the hero text). A still image should be added in case the user has accessibility options checked.

add hero to home, align h1 to the left

---

app/models/vehicle.rb
app/views/vehicles/index.html.erb

add overflow to index vehicle description and maximum chars for vehicle description validation

index vehicle description overflow

---

app/controllers/vehicles_controller.rb
app/views/vehicles/edit.html.erb
config/routes.rb

Edit vehicle

---

app/assets/stylesheets/components/_carroussel.scss
app/assets/stylesheets/components/_index.scss
app/controllers/vehicles_controller.rb
app/models/vehicle.rb
app/views/layouts/application.html.erb
app/views/vehicles/_carouselshow.html.erb
app/views/vehicles/_carroussel.html.erb
app/views/vehicles/_form.html.erb
app/views/vehicles/index.html.erb
app/views/vehicles/show.html.erb
db/seeds.rb
package.json
yarn.lock

Carrossel do index e das views criados. 
Para que o usuário possa acrescentar mais fotos, alterei o form e o model de vehicles para aceitar mais de uma foto.

Carroussel

---

app/controllers/orders_controller.rb
app/views/orders/show.html.erb
app/views/vehicles/new.html.erb
app/views/vehicles/show.html.erb
test/models/garage_test.rb

links remanescentes viraram botões.

inseri os botões nos links

---

app/controllers/vehicles_controller.rb
app/javascript/controllers/masks_controller.js
app/views/vehicles/_form.html.erb
app/views/vehicles/show.html.erb
db/migrate/20220307213254_change_vehicle_price_column.rb
db/migrate/20220307214111_change_vehicle_price.rb
db/schema.rb

finally! added currency format to form and vehicle show

Fix currency

---

Gemfile
app/controllers/vehicles_controller.rb
app/models/vehicle.rb
app/views/vehicles/index.html.erb

A linha 10 do index.html.erb teve que ser comentada para o search funcionar. Felipe está verificando.

fix search completed

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search_bar.scss
app/assets/stylesheets/pages/_home.scss
app/views/vehicles/_search-bar.html.erb
app/views/vehicles/index.html.erb

made a section with search and create vehicle side by side

add combined section with search and create button to index

---

app/assets/stylesheets/components/_form.scss
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/vehicles/edit.html.erb
app/views/vehicles/new.html.erb

Fix title margins between title and nav

fix title margins on forms

---

app/assets/stylesheets/components/_carroussel.scss
app/views/vehicles/_carroussel.html.erb
app/views/vehicles/index.html.erb

fixed carroussel images so they are all the same, fixed search when user is not logged in

fix carroussel height size
